/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Foo: typeof import('./src/components/Foo.vue')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.10.0-beta.1_@babel+parser@7.26.3_rollup@4.30.1/node_modules/iles/dist/client/app/components/Island.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
