// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Foo: typeof import('./src/components/Foo.vue')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.9.2/node_modules/iles/dist/client/app/components/Island.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
